# This is a basic workflow to help you get started with Actions
name: Create Zip

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env:
      RELEASE_NAME: PUT_YOUR_RELEASE_NAME_HERE
      GNUTARGET: default

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup Release Version
      run: |
        echo "RELEASE_NAME=PUT_YOUR_RELEASE_NAME_HERE_$" >> $GITHUB_ENV
      shell: bash
      if: github.event_name == 'release' && github.event.action == 'published'

    - name: Setup Environment
      run: | 
        dir
        mkdir build
        cd build
        mkdir $
        cd ../../NautilusStudios-ProjectII_RPG
        dir
        
      # Setup MSBuild.exe path if required
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build Solution (MSVC16)
      run: |
        msbuild.exe Imperial_Fall.sln  /property:Configuration=Release
        copy /Y Imperial_Fall\build\Release\Game.exe build\$\Game.exe
      shell: cmd
      
    - name: Generate Artifacts
      run: |
        robocopy .\Output .\build\$\Output /S
        robocopy .\build\$ .\build\$\Output Game.exe /MOVE
        copy /Y .\README.md .\build\$\README.md
        copy /Y .\LICENSE .\build\$\LICENSE
        cd build
        7z a ./$.zip
        dir
      shell: cmd

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Imperial_fall.zip
        path: ./build/$.zip
